IRIS Classification (붓꽃데이터셋을 이용한 ML)
------------------

![붓꽃 이미지](./iris_images/1.png)

### kaggle Site

https://www.kaggle.com/c/iris-dataset-test-competition

In [3]:
from sklearn.datasets import load_iris

### Data load

In [4]:
iris_dataset = load_iris()
print("iris_dataset key: \n{}".format(iris_dataset.keys()))

iris_dataset key: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [5]:
print(iris_dataset.data[:3]) # Print 2 cell 
iris_dataset['data'][:2]

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [6]:
# count row & column 
iris_dataset.data.shape

(150, 4)

In [7]:
print(iris_dataset.target)
iris_dataset.target_names

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [8]:
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

### 2. train data & test data

### scikit-learn에서 제공하는 train_test_split 함수 사용

### 훈련데이터 75%, 테스트 데이터 25%로 나누어 준다.

### X_train(훈련데이터 문제), Y_train(훈련데이터 답)

### X_test(테스트데이터 문제), Y_test(테스트데이터 답)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=42)

In [11]:
# 훈련 데이터의 문제와 답 건수 확인
print(X_train.shape)
Y_train.shape

(112, 4)


(112,)

In [12]:
# 테스트 데이터의 문제와 답 건수 확인
print(X_test.shape)
Y_test.shape

(38, 4)


(38,)

In [13]:
print(X_test[:5])
Y_test[:5]

[[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]]


array([1, 0, 2, 1, 1])

### 3.kNN(K-Neighbors near) 최급접 이웃 분류기(classification) 알고리즘 선택

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
knn = KNeighborsClassifier(n_neighbors=1)

### 4.학습하기와 예측하기

In [16]:
knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

### 5. 예측하기

In [17]:
import numpy as np

In [18]:
X_new = np.array([[6.1, 2.8, 4.7, 1.2]])
X_new

array([[6.1, 2.8, 4.7, 1.2]])

In [19]:
prediction = knn.predict(X_new)
prediction

array([1])

In [20]:
iris_dataset.target_names[prediction]

array(['versicolor'], dtype='<U10')

In [21]:
# 예측된 모델 평가하기
Y_pred = knn.predict(X_test)
Y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [22]:
print('test accurance {:.2f}'.format(np.mean(Y_pred == Y_test)))

test accurance 1.00


In [23]:
print('test set accurance{:.2f}'.format(knn.score(X_test, Y_test)))

test set accurance1.00
